%% CALL parglm_torch.py, and execute the test_grid.py script.
% Use the absolute path for parglm_test_cases, from your MATLAB console.
% This test uses similar parameters, and you can compare the F_ratios.
% Results should be within a tolerance 1e-6.

folder = 'parglm_test_cases';   % test dir

files = dir(fullfile(folder, '*.mat'));

% sort by numeric index
names = {files.name};
idx = cellfun(@(s) sscanf(s, 'case_%d.mat'), names);
[~, ord] = sort(idx);
files = files(ord);

for k = 1:numel(files)
    S = load(fullfile(folder, files(k).name));

    X = double(S.X);
    F = double(S.F);
    ci = double(S.case_index);   % 0-based (from Python)

    fprintf('\n=== Case %d: %s ===\n', ci, files(k).name);

    switch ci
        case 0
            % Model="linear", Ts=1, Random=[0 0], Ordinal=[0 0], Coding=[0 0], Nested=[]
            T = parglm(X, F, ...
                'Model', 'linear', ...
                'Preprocessing', 2, ...
                'Permutations', 1, ...
                'Ts', 1, ...
                'Random', [0 0], ...
                'Ordinal', [0 0], ...
                'Coding', [0 0], ...
                'Nested', []);

        case 1
            % Model="linear", Ts=2, Random=[0 1]
            T = parglm(X, F, ...
                'Model', 'linear', ...
                'Preprocessing', 2, ...
                'Permutations', 1, ...
                'Ts', 2, ...
                'Random', [0 1], ...
                'Ordinal', [0 0], ...
                'Coding', [0 0], ...
                'Nested', []);

        case 2
            % Model=[[0,1]] -> MATLAB Model={ [1 2] }, Ts=1, Random=[0 0]
            T = parglm(X, F, ...
                'Model', { [1 2] }, ...
                'Preprocessing', 2, ...
                'Permutations', 1, ...
                'Ts', 1, ...
                'Random', [0 0], ...
                'Ordinal', [0 0], ...
                'Coding', [0 0], ...
                'Nested', []);

        case 3
            % Model={ [1 2] }, Ts=2, Random=[0 1]
            T = parglm(X, F, ...
                'Model', { [1 2] }, ...
                'Preprocessing', 2, ...
                'Permutations', 1, ...
                'Ts', 2, ...
                'Random', [0 1], ...
                'Ordinal', [0 0], ...
                'Coding', [0 0], ...
                'Nested', []);

        case 4
            % Model={ [1 2] }, Ts=2, Random=[0 0 1], Nested=[[0,2]] -> [1 3]
            T = parglm(X, F, ...
                'Model', { [1 2] }, ...
                'Preprocessing', 2, ...
                'Permutations', 1, ...
                'Ts', 2, ...
                'Random', [0 0 1], ...
                'Ordinal', [0 0 0], ...
                'Coding', [0 0 0], ...
                'Nested', [1 3]);

        case 5
            % Model={ [1 2] }, Ts=2, Random=[0 1 1], Nested=[1 3]
            T = parglm(X, F, ...
                'Model', { [1 2] }, ...
                'Preprocessing', 2, ...
                'Permutations', 1, ...
                'Ts', 2, ...
                'Random', [0 1 1], ...
                'Ordinal', [0 0 0], ...
                'Coding', [0 0 0], ...
                'Nested', [1 3]);

        otherwise
            error('Unexpected case_index=%d', ci);
    end

    Fvals = T.F(~isnan(T.F));
    disp(Fvals - S.F_ratios'); % transpose the elements extracted from Python.

end